const sales = [
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-01',
        product: 'carrots',
        sales: 103,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-01',
        product: 'potatoes',
        sales: 270,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-01',
        product: 'corn',
        sales: 71,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-01',
        product: 'green beans',
        sales: 29,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-01',
        product: 'apples',
        sales: 210,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-01',
        product: 'peaches',
        sales: 155,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-01',
        product: 'pears',
        sales: 183,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-01',
        product: 'plums',
        sales: 112,
    },
    {
        category: 'produce',
        subcategory: 'meat',
        date: '2020-06-01',
        product: 'beef',
        sales: 577,
    },
    {
        category: 'produce',
        subcategory: 'meat',
        date: '2020-06-01',
        product: 'chicken',
        sales: 350,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-02',
        product: 'carrots',
        sales: 102,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-02',
        product: 'potatoes',
        sales: 241,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-02',
        product: 'corn',
        sales: 59,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-02',
        product: 'green beans',
        sales: 31,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-02',
        product: 'apples',
        sales: 274,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-02',
        product: 'peaches',
        sales: 180,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-02',
        product: 'pears',
        sales: 196,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-02',
        product: 'plums',
        sales: 58,
    },
    {
        category: 'produce',
        subcategory: 'meat',
        date: '2020-06-02',
        product: 'beef',
        sales: 464,
    },
    {
        category: 'produce',
        subcategory: 'meat',
        date: '2020-06-02',
        product: 'chicken',
        sales: 334,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-03',
        product: 'carrots',
        sales: 83,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-03',
        product: 'potatoes',
        sales: 249,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-03',
        product: 'corn',
        sales: 67,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-03',
        product: 'green beans',
        sales: 46,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-03',
        product: 'apples',
        sales: 295,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-03',
        product: 'peaches',
        sales: 187,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-03',
        product: 'pears',
        sales: 244,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-03',
        product: 'plums',
        sales: 105,
    },
    {
        category: 'produce',
        subcategory: 'meat',
        date: '2020-06-03',
        product: 'beef',
        sales: 403,
    },
    {
        category: 'produce',
        subcategory: 'meat',
        date: '2020-06-03',
        product: 'chicken',
        sales: 442,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-04',
        product: 'carrots',
        sales: 93,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-04',
        product: 'potatoes',
        sales: 269,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-04',
        product: 'corn',
        sales: 50,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-04',
        product: 'green beans',
        sales: 54,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-04',
        product: 'apples',
        sales: 228,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-04',
        product: 'peaches',
        sales: 155,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-04',
        product: 'pears',
        sales: 163,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-04',
        product: 'plums',
        sales: 118,
    },
    {
        category: 'produce',
        subcategory: 'meat',
        date: '2020-06-04',
        product: 'beef',
        sales: 558,
    },
    {
        category: 'produce',
        subcategory: 'meat',
        date: '2020-06-04',
        product: 'chicken',
        sales: 397,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-05',
        product: 'carrots',
        sales: 94,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-05',
        product: 'potatoes',
        sales: 254,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-05',
        product: 'corn',
        sales: 61,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-05',
        product: 'green beans',
        sales: 50,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-05',
        product: 'apples',
        sales: 236,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-05',
        product: 'peaches',
        sales: 180,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-05',
        product: 'pears',
        sales: 246,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-05',
        product: 'plums',
        sales: 108,
    },
    {
        category: 'produce',
        subcategory: 'meat',
        date: '2020-06-05',
        product: 'beef',
        sales: 412,
    },
    {
        category: 'produce',
        subcategory: 'meat',
        date: '2020-06-05',
        product: 'chicken',
        sales: 498,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-06',
        product: 'carrots',
        sales: 95,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-06',
        product: 'potatoes',
        sales: 303,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-06',
        product: 'corn',
        sales: 52,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-06',
        product: 'green beans',
        sales: 57,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-06',
        product: 'apples',
        sales: 249,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-06',
        product: 'peaches',
        sales: 181,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-06',
        product: 'pears',
        sales: 167,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-06',
        product: 'plums',
        sales: 75,
    },
    {
        category: 'produce',
        subcategory: 'meat',
        date: '2020-06-06',
        product: 'beef',
        sales: 462,
    },
    {
        category: 'produce',
        subcategory: 'meat',
        date: '2020-06-06',
        product: 'chicken',
        sales: 382,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-07',
        product: 'carrots',
        sales: 102,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-07',
        product: 'potatoes',
        sales: 295,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-07',
        product: 'corn',
        sales: 59,
    },
    {
        category: 'produce',
        subcategory: 'vegetables',
        date: '2020-06-07',
        product: 'green beans',
        sales: 62,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-07',
        product: 'apples',
        sales: 211,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-07',
        product: 'peaches',
        sales: 173,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-07',
        product: 'pears',
        sales: 243,
    },
    {
        category: 'produce',
        subcategory: 'fruit',
        date: '2020-06-07',
        product: 'plums',
        sales: 93,
    },
    {
        category: 'produce',
        subcategory: 'meat',
        date: '2020-06-07',
        product: 'beef',
        sales: 529,
    },
    {
        category: 'produce',
        subcategory: 'meat',
        date: '2020-06-07',
        product: 'chicken',
        sales: 399,
    },
];
